##
# uWSGI configuration for udata worker
# Este ficheiro é configurado para gerir um único processo do Celery worker. 
# O paralelismo é controlado pelo próprio Celery (com o --concurrency=16). 
# Por isso, a diretiva processes do uWSGI deve ser 1 para evitar conflitos.
##

[uwsgi]
; Ativa o modo mestre uWSGI.
master = true
; Define o número de processos do uWSGI (neste caso, 1). Este processo gerencia o Celery.
processes = 1
; Define a variável de ambiente para a localização do ficheiro de configuração do udata.
; (O container corre como utilizador não-root `udata`, por isso C_FORCE_ROOT não é necessário.)
env = UDATA_SETTINGS=%d/../udata.cfg

; Inicia e monitoriza o Celery worker. Se o processo parar, o uWSGI reinicia-o.
smart-attach-daemon = /tmp/celery-worker.pid celery -A udata.worker worker --events --concurrency=16 --pidfile=/tmp/celery-worker.pid -n worker1@%h
; Garante que o processo Celery é encerrado corretamente quando o uWSGI é desligado.
exec-as-user-atexit = kill -TERM `cat /tmp/celery-worker.pid`

; Harakiri preventivo
; Encerra workers que estejam a demorar mais de 300 segundos a responder.
harakiri = 300

; Logging configuration
; Define o nível de detalhe do log.
log-level = info
; Permite que o processo mestre do uWSGI gere logs.
log-master = true
; Redireciona mensagens de erro específicas para este ficheiro.
logto = /logs/app.log
; Regista erros HTTP 5xx que possam ocorrer.
log-5xx = true
