services:
  app:
    container_name: udata-backend-app
    build: .
    command: uv run gunicorn udata.wsgi:app --bind 0.0.0.0:7000 --workers 4 --threads 2 --timeout 120
    ports:
      - '7000:7000'
    volumes:
      - ./udata.cfg:/app/udata.cfg:ro
      - ./udata/auth/saml/credentials:/app/udata/auth/saml/credentials:ro
      - ${FS_ROOT:-/home/adbrum/workspace/babel/udata-front-pt/udata-fs}:/udata/fs
      - app-logs:/logs
    env_file:
      - .env
    environment:
      UDATA_SETTINGS: /app/udata.cfg
      FS_ROOT: /udata/fs
    restart: unless-stopped

  worker:
    container_name: udata-backend-worker
    build: .
    command: uv run celery -A udata.worker worker --events --concurrency=4 -l info
    volumes:
      - ./udata.cfg:/app/udata.cfg:ro
      - ./udata/auth/saml/credentials:/app/udata/auth/saml/credentials:ro
      - ${FS_ROOT:-/home/adbrum/workspace/babel/udata-front-pt/udata-fs}:/udata/fs
      - app-logs:/logs
    env_file:
      - .env
    environment:
      UDATA_SETTINGS: /app/udata.cfg
      C_FORCE_ROOT: 'true'
      FS_ROOT: /udata/fs
    restart: unless-stopped

  beat:
    container_name: udata-backend-beat
    build: .
    command: uv run celery -A udata.worker beat -l info
    volumes:
      - ./udata.cfg:/app/udata.cfg:ro
      - app-logs:/logs
    env_file:
      - .env
    environment:
      UDATA_SETTINGS: /app/udata.cfg
      C_FORCE_ROOT: 'true'
    restart: unless-stopped

volumes:
  app-logs:
