/opt/dadosgov/backend/logs/*.log {
    su dadosgov dadosgov
    daily
    size 10M
    rotate 50
    compress
    delaycompress
    missingok
    notifempty
    dateext
    dateformat .%Y-%m-%d-%s
    copytruncate
}
